### ISSUE TITLE
No /frontend/buildEnvVars.js File

### ISSUE THREAD

**Issue by SePreuss** [aws-samples/promptus#2]
Hello, 

I ran the setup of the scripts and got some errors because the file "/frontend/buildEnvVars.js" does not exist. It is executed in the bash scripts you provided. I think this file is necessary to create the files "bucketName.txt" and "distributionUrl.txt".  

Did I miss something?

**Comment by JWThewes** [comment]
Fixed with commit 7f18f485cd4d3dd38d267e53cbde55b91530adfb

**Comment by JWThewes** [comment]
Fixed with commit https://github.com/aws-samples/promptus/commit/7f18f485cd4d3dd38d267e53cbde55b91530adfb

**Comment by SePreuss** [comment]
Hey thank you, 
but the file was not added in the commit "Add buildEnvVars.js file".

**Comment by JWThewes** [comment]
So sorry. That was my mistake. It's fixed already
